name = 's1_mnist_3x1024'

[dnn]
	artifact = 'MNIST'
	onnx = './configs/networks/mnist_3x1024.onnx'
	r4v_config = './configs/networks/mnist_3x1024.toml'
	data_config = './configs/data/mnist.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 2

	[ca.parameters]
		[ca.parameters.explicit]
			neu  = [0.33,0.66,1.0,1.33,1.66,2.0]
			fc   = [0.33,0.66,1.0,1.33,1.66,2.0]
			idm  = [0.33,0.66,1.0,1.33,1.66,2.0]
			ids  = [0.33,0.66,1.0,1.33,1.66,2.0]
			eps  = [0.33,0.66,1.0,1.33,1.66,2.0]
			prop = [0,1,2,3,4]

#			neu  = [0.33,0.66,1.00]
#			fc   = [0.33,0.66,1.00]
#			idm  = [0.33,0.66,1.00]
#			ids  = [0.33,0.66,1.00]
#			eps  = [0.33,0.66,1.00]
#			prop = [0,1,2,3,4]

	#[ca.constraints]

[train]
	epochs = 10
	drop_scheme = 'random'
	add_scheme = 'same_as_last_relu'

	[train.dispatch]
		nb_gpus = 1
		platform = "local"
		exclude = 'ai06,lynx01,ristretto01,ristretto02,ristretto03,ristretto04,affogato13,affogato14,affogato15'


[verify]
	debug = true
	skip_layers = 3
	eps = 0.02
	time = 600
	memory = '16G'
	GRB_LICENSE_FILE="./lib/gurobi.lic"
	[verify.verifiers]
		DNNV = ['eran_deepzono','eran_deeppoly','neurify','nnenum']
		# DNNF = ['default']

	[verify.dispatch]
		platform = "local"
		reservation = "dx3yy_23"
		nb_cpus = 6
		nodes = ['cortado01','cortado02','cortado03','cortado04','cortado05','cortado06','cortado07','cortado08','cortado09']
		task_per_node = 7