name = 'REevo_edz_debug_new'

[dnn]
	artifact = 'MNIST'
	onnx = './configs/networks/mnist_3x1024.onnx'
	r4v_config = './configs/networks/mnist_3x1024.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 3

	[ca.parameters]
		[ca.parameters.level]
			neu = 11
			fc = 19
			prop = 5

		[ca.parameters.range]
			neu = ['71/33', '131/33']
			fc = ['1/3', '578/33']
			prop = [0, 4]

[evolutionary]
	iterations = 1
	arity = 2
	inflation_rate = 2
	deflation_rate = 0.5

	parameters = ['neu', 'fc']
	parameters_upper_bounds = {'fc'='128/3'}

[train]
	epochs = 10
	drop_scheme = 'random'
	add_scheme = 'same_as_last_relu'

	[train.dispatch]
		nb_gpus = 1
		platform = "slurm"
		exclude = """ai01,ai02,ai03,ai04,ai05,\
				   affogato12,affogato13,affogato14,\
				   adriatic02,adriatic03,adriatic04,adriatic05,adriatic06,\
			   	   lynx01,lynx02,lynx04,lynx05,lynx06,lynx07,cheetah01,lotus"""

[verify]
	debug = true
	eps = 0.02
	time = 600
	memory = '16G'
	[verify.verifiers]
		DNNV_wb = ['eran_deepzono']
		# DNNV = ['eran_deeppoly','neurify','nnenum']
		# DNNF = ['default']

	[verify.dispatch]
		platform = "slurm"
		#reservation = "dx3yy_28"
		nb_cpus = 6
		nodes = ['cortado02','cortado03','cortado04','cortado05','cortado06','cortado07','cortado08','cortado09']
		task_per_node = 7
