[distillation]
maxmemory="32G"
threshold=1e-9
cuda=true
type="classification"
precompute_teacher=true
save_intermediate=false

[distillation.parameters]
epochs=10
optimizer="adam"
loss="MSE"
learning_rate=1e-3

[distillation.data]
format="cifar"
batchsize=64
presized=false
path="./data/cifar"

[distillation.teacher]
framework="onnx"
input_shape=[1, 3, 32, 32]
input_format="NCHW"
model="./configs/networks/cifar_conv_big.onnx"

[distillation.data.transform.teacher]
grayscale=false
mean=[0.4914, 0.4822, 0.4465]
std=[0.2023, 0.1994, 0.201]
height=32
width=32
min_value=-2.4290657
max_value=2.7537313

[distillation.data.transform.student]
grayscale=false
mean=[0.4914, 0.4822, 0.4465]
std=[0.2023, 0.1994, 0.201]
height=32
width=32
min_value=-2.4290657
max_value=2.7537313

[distillation.data.train]
shuffle=true

[distillation.data.validation]
shuffle=false