[distillation]
maxmemory="64G"
threshold=1e-9
cuda=true
type="regression"
precompute_teacher=true

[distillation.parameters]
epochs=10
optimizer="adadelta"
rho=0.95
loss="MSE"
learning_rate=0.01

[distillation.data]
format="udacity-driving"
batchsize=256
presized=false

[distillation.teacher]
framework="onnx"
input_shape=[1, 100, 100, 3]
input_format="NHWC"
model="./configs/networks/dave.onnx"

[distillation.data.transform.teacher]
bgr=true
mean=[103.939, 116.779, 123.68]
max_value=255.0
height=100
width=100

[distillation.data.transform.student]
bgr=true
mean=[103.939, 116.779, 123.68]
max_value=255.0
height=100
width=100

[distillation.data.train]
shuffle=true

[distillation.data.train.teacher]
path="data/udacity.sdc.100/training"

[distillation.data.train.student]
path="data/udacity.sdc.100/training"

[distillation.data.validation]
shuffle=false

[distillation.data.validation.teacher]
path="data/udacity.sdc.100/validation"

[distillation.data.validation.student]
path="data/udacity.sdc.100/validation"

