name = 's1_dave'

[dnn]
	onnx = "./configs/networks/dave.onnx"
	r4v_config = "./configs/networks/dave.toml"
	data_config = "./configs/data/udacity-driving.toml"
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 1

[ca]
	strength = 2

    [ca.parameters]
		[ca.parameters.level]
			neu = 10
			fc = 5
    		conv = 6
			idm = 10
			ids = 10
			eps = 10
			prop = 10

		[ca.parameters.range]
			neu = [0.1,1.0]
			fc = [0,1]
    		conv = [0,1]
			idm = [0.1,1.0]
			ids = [0.1,1.0]
			eps = [0.1,1.0]
			prop = [0,9]
	
	[ca.constraints]
		value = [
		'fc=0 => conv!=0',
		'conv=0 => neu=0',
		'conv=4 => idm>0',
		'conv=5 => idm>2',
		'conv=0 && neu=0 => idm<8',
		'conv=1 && idm=0 => neu<3'
		]

[train]
	epochs = 10
	
	[train.dispatch]
		gpu = true
		platform = "slurm"
		exclude = 'ai06,affogato11,affogato12,affogato13,affogato14,affogato15,lynx01,lynx02,lynx03,lynx04,lynx05,lynx06,lynx07'


[verify]
	debug = false
	rm_transpose = false
	eps = 2
	time = 14400
	memory = '64G'
	GRB_LICENSE_FILE="./lib/gurobi.lic"
	verifiers = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex','dnnf','marabou','nnenum','mipverify','verinet']

	[verify.dispatch]
		gpu = false
		platform = "slurm"
		reservation = "dx3yy_28"
		nb_cpus = 6
		nodes = ['cortado04','cortado05','cortado06','cortado07','cortado08','cortado09','cortado10']
		task_per_node = 7