name = 'acas'

[dnn]
	onnx = './configs/networks/acas_1_1.onnx'
	r4v_config = './configs/networks/acas.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 2

    [ca.parameters]
		[ca.parameters.level]
			neu = 5
			fc = 6
			#conv = 5
			#idm = 5
			ids = 5
			#eps = 5
			prop = 5

		[ca.parameters.range] # 0~1
			neu = [0.2,1.0]
			fc = [0.16666666666666666,1.0]
    		#conv = [0,1]
			#idm = [0.2,1.0]
			ids = [0.2,1.0]
			#eps = [0.2,1.0]
			prop = [0,1]

[train]
	epochs = 50

[verify]
	time = 14400
	memory = '64G'
	verifiers = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex']

[dispatch]
	mode = 'slurm'
	
	[dispatch.slurm]
		nodes = ['slurm1','slurm2','slurm3','slurm4','slurm5']
		task_per_node = [7,7,7,7,3]
		reservation = 'dls2fc_7'
