name = 'acas'

[dnn]
	artifact = 'ACAS'
	onnx = './configs/networks/acas_1_1.onnx'
	r4v_config = './configs/networks/acas.toml'
	data_config = "./configs/data/acas.toml"
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 2

    [ca.parameters]
		[ca.parameters.level]
			neu = 5
			fc = 6
			#conv = 5
			#idm = 5
			#ids = 5
			#eps = 5
			prop = 9

		[ca.parameters.range] # 0~1
			neu = [0.5,1.0]
			fc = [0.16666666666666666,1.0]
    		#conv = [0,1]
			#idm = [0.2,1.0]
			#ids = [0.2,1.0]
			#eps = [0.2,1.0]
			prop = [0,8]

[train]
	epochs = 2
	drop_scheme = 'random'

	[train.dispatch]
		platform = "local"

[verify]
	debug = true
	skip_layers = 0
	time = 300
	memory = '8G'
	[verify.verifiers]
		DNNV = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex','marabou','nnenum','mipverify','verinet']
		DNNF = ['default']

	[verify.dispatch]
		platform = "local"