network_name = "acas"
source_model = "configs/networks/acas.onnx"
source_distillation_config = "configs/networks/acas.toml"
data_config = "configs/data/acas.toml"
parameter_limit = 2116983
veri_time = 14400
veri_mem = 64
verifiers = [ "neurify",]

[dis_threshold]
type = "loss"
value = [ 0.01, 0.01,]

[factor]
[factor.architecture]
neuron_bins = 10
layer_depth_step = 1
layer_types = ['FC','Conv']
[factor.property]
count = 5
epsilons = [0.01,0.02,0.05,0.1,0.2]
[factor.other]
weight_value_repeats = 2