root = "/p/d4v/dx3yy/nas_res_s1"
nb_best_net = 5
mode = "bs"
network_name = "dave"
original_model = "/p/d4v/dx3yy/DNNVeri/dnnvbs/cegsdl/networks/dave/model.onnx"
source_distillation_config = "/p/d4v/dx3yy/DNNVeri/dnnvbs/configs/dave.toml"
proxy_dis_epochs = 12
scale_layer_factor = 0.5
veri_time = 14400
veri_mem = 64
proxy_nb_props = 10
veri_threshold = [ 1, 1,]
verifiers = [ "neurify",]
scale_limit_strat = 'nb_layers'
#scale_network_size_distance = 0.1
max_nb_layer_scale = 1

[dis_threshold.dave]
type = "loss"
value = [ 0.01, 0.01,]
