name = 'dave'

[dnn]
	artifact = 'DAVE2'
	onnx = "./configs/networks/dave.onnx"
	r4v_config = "./configs/networks/dave.toml"
	data_config = "./configs/data/udacity-driving.toml"
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 1

[ca]
	strength = 2

	[ca.parameters.level]
		neu = 5
		fc = 5
    	conv = 6
		idm = 5
		ids = 5
		eps = 5
		prop = 5

	[ca.parameters.range]
		neu = [0.2,1.0]
		fc = [0,1]
    	conv = [0,1]
		idm = [0.2,1.0]
		ids = [0.2,1.0]
		eps = [0.2,1.0]
		prop = [0,4]

	
	[ca.constraints]
		value = [
		'fc=0 => conv!=0',
		'conv=0 => neu=0',
		'conv=5 => idm!=0',
		'conv=0 && neu=0 => idm <4'
		]

[train]
	epoches = 10
	drop_scheme = 'random'
	[train.dispatch]
		platform = 'local'
		gpu = false


[verify]
	eps = 2
	time = 14400
	memory = '64G'
	GRB_LICENSE_FILE="./lib/gurobi.lic"
	verifiers = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex']

	[verify.dispatch]
		platform = 'local'