[distillation]
maxmemory="32G"
threshold=1e-9
cuda=true
type="regression"
precompute_teacher=true

[distillation.parameters]
epochs=10
optimizer="adadelta"
rho=0.95
loss="MSE"

[distillation.data]
format="udacity-driving"
batchsize=256
presized=false

[distillation.data.transform]
bgr=true
mean=[103.939, 116.779, 123.68]
max_value=255.0
height=100
width=100

[distillation.data.train]
shuffle=true

[distillation.data.train.teacher]
path="/p/d4v/dls2fc/cegsdl/artifacts/udacity.sdc.100/training"

[distillation.data.train.student]
path="/p/d4v/dls2fc/cegsdl/artifacts/udacity.sdc.100/training"

[distillation.data.validation]
shuffle=false

[distillation.data.validation.teacher]
path="/p/d4v/dls2fc/cegsdl/artifacts/udacity.sdc.100/validation"

[distillation.data.validation.student]
path="/p/d4v/dls2fc/cegsdl/artifacts/udacity.sdc.100/validation"

[distillation.teacher]
framework="onnx"
input_shape=[1, 100, 100, 3]
input_format="NHWC"
model="/p/d4v/dx3yy/DNNVeri/dnnvbs/cegsdl/networks/dave/model.onnx"

