name = 'dave'

[dnn]
	artifact = 'DAVE2'
	onnx = "./configs/networks/dave.onnx"
	r4v_config = "./configs/networks/dave.toml"
	data_config = "./configs/data/udacity-driving.toml"
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 1

[ca]
	strength = 2

	[ca.parameters.level]
		neu = 5
		fc = 5
    	conv = 6
		idm = 5
		ids = 5
		eps = 5
		prop = 5

	[ca.parameters.range]
		neu = ['1/5','1']
		fc = ['0','1']
    	conv = ['0','1']
		idm = ['1/5','1']
		ids = ['1/5','1']
		eps = ['1/5','1']
		prop = ['0','4']

	
	# prevent invalid network specifications
	[ca.constraints]
		value = [
			'fc=0 => conv!=0',
			'conv=0 => neu=0',
			'conv=5 => idm!=0',
			'conv=0 && neu=0 => idm <4'
		]

[train]
	epoches = 10
	drop_scheme = 'random'

	[train.dispatch]
		platform = 'local'
		gpu = false


[verify]
	eps = 2 #2 out of 255
	time = 14400
	memory = '64G'
	GRB_LICENSE_FILE="./lib/gurobi.lic" #path to gurobi licence

	[verify.verifiers]
		# requires full installation of DNNV, including all verifiers
		DNNV = ['eran_deepzono',
				'eran_deeppoly',
				'eran_refinezono',
				'eran_refinepoly',
				'neurify',
				'planet',
				'bab',
				'bab_sb',
				'reluplex',
				'marabou',
				'nnenum',
				'mipverify',
				'verinet']
		
		# requires installation of DNNF
		DNNF = ['default']

		# requires installation of of SwarmHost
		SwarmHost = ['abcrown',
					 'neuralsat',
					 'mnbab',
					 'nnenum',
					 'verinet']

	[verify.dispatch]
		platform = "local"