name = 'dave_enu2_cov3_low3'

[dnn]
	onnx = "./configs/networks/dave.onnx"
	r4v_config = "./configs/networks/dave.toml"
	data_config = "./configs/data/udacity-driving.toml"
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 1

[ca]
	strength = 4

	[ca.parameters.level]
		neu = 3
		fc = 3
    	conv = 3
		idm = 3
		ids = 3
		eps = 3
		prop = 3

	[ca.parameters.enumerate]
		neu = [0.05, 0.1, 0.15]
		prop = [0, 1, 2]

	[ca.parameters.range]
		fc = [0.0,0.5]
		conv = [0.0,0.4]
		idm = [0.2,0.6]
		ids = [0.2,0.6]
		eps = [0.2,0.6]

	[ca.constraints]
		value = ['fc=0 => conv!=0']

[train]
	epochs = 50
	[train.dispatch]
		gpu = true
		platform = "slurm"
		#reservation = "dx3yy_9"
		#nodes = ['ristretto01','ristretto02','ristretto03','ristretto04']
		#task_per_node = 8

[verify]
	eps = 2
	#time = 14400
	time = 3600
	memory = '64G'
	GRB_LICENSE_FILE="./lib/gurobi.lic"
	verifiers = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex','dnnf']

	[verify.dispatch]
		gpu = false
		platform = "slurm"
		#reservation = "dx3yy_10"
		nodes = ['cortado01','cortado02','cortado03','cortado04','cortado05','cortado06','cortado07','cortado08','cortado09']
		task_per_node = 7
