name = 'dave_2x2_enu'

[dnn]
	onnx = "./configs/networks/dave.onnx"
	r4v_config = "./configs/networks/dave.toml"
	data_config = "./configs/data/udacity-driving.toml"
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 1

[ca]
	strength = 2

	[ca.parameters.level]
		neu = 5
		fc = 3
    	conv = 4
		idm = 5
		ids = 5
		eps = 5
		prop = 5

	[ca.parameters.enumerate]
		neu = [0.04, 0.08, 0.16, 0.32, 0.64]
		prop = [0, 1, 2, 3, 4]

	[ca.parameters.range]
		fc = [0.5,1.0]
		conv = [0.4,1.0]
		idm = [0.2,1.0]
		ids = [0.2,1.0]
		eps = [0.2,1.0]


	
	[ca.constraints]
		value = ['conv=3 => idm!=0']

[train]
	epoches = 10
	[train.dispatch]
		gpu = true
		platform = "slurm"
		reservation = "dx3yy_9"
		nodes = ['ristretto01','ristretto03','ristretto04']
		task_per_node = 8

[verify]
	eps = 2
	time = 14400
	memory = '64G'
	GRB_LICENSE_FILE="./lib/gurobi.lic"
	verifiers = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex']

	[verify.dispatch]
		gpu = false
		platform = "slurm"
		reservation = "dx3yy_10"
		nodes = ['cortado01','cortado02','cortado03','cortado04','cortado05','cortado06','cortado07','cortado08','cortado09','cortado10']
		task_per_node = 7
