name = 'mcb'

[dnn]
	artifact = 'MNIST'
	onnx = './configs/networks/mnist_conv_big.onnx'
	r4v_config = './configs/networks/mnist_conv_big.toml'

[ca]
	strength = 2

	[ca.parameters]
		[ca.parameters.level]
			neu = 5
			fc = 3
			conv = 5
			idm = 5	
			ids = 5
			eps = 5
			prop = 5

		[ca.parameters.range]
			neu = ['1/5','1']
			fc = ['0','1']
    		conv = ['0','1']
			idm = ['1/5','1']
			ids = ['1/5','1']
			eps = ['1/5','1']
			prop = ['0','4']

	# prevent invalid network specifications
	[ca.constraints]
		value = ['fc=0 => conv!=0',
		'(fc=2 && conv=0 && idm=0) => neu<4']

[train]
	epochs = 10
	drop_scheme = 'random'

	[train.dispatch]
		platform = 'local'

[verify]
	eps = 0.02 # 0.02 out of 1
	time = 14400
	memory = '64G'

	[verify.verifiers]
		# requires full installation of DNNV, including all verifiers
		DNNV = ['eran_deepzono',
				'eran_deeppoly',
				'eran_refinezono',
				'eran_refinepoly',
				'neurify',
				'planet',
				'bab',
				'bab_sb',
				'reluplex']

	[verify.dispatch]
		platform = "local"