name = 'mcb'

[dnn]
	onnx = './configs/networks/mnist_conv_big.onnx'
	r4v_config = './configs/networks/mnist_conv_big.toml'
	data_config = './configs/data/mnist.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 3

    [ca.parameters]
		neu = 5
		fc = 3
    	conv = 5
		idm = 5
		ids = 5
		eps = 5
		prop = 5
	
	[ca.constraints]
		value = ['fc=0 => conv!=0',
		'(fc=2 && conv=0 && idm=0) => neu<4']

[train]
	epoches = 10

[verify]
	eps = 0.02
	time = 14400
	memory = '64G'
	verifiers = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','mipverify','reluplex']

[dispatch]
	mode = 'slurm'

	[dispatch.slurm]
		nodes = ['slurm1','slurm2','slurm3','slurm4','slurm5']
		task_per_node = [7,7,7,7,3]
		reservation = 'dls2fc_7'