name = 'mcbl'

[dnn]
	onnx = './configs/networks/mnist_conv_big.onnx'
	r4v_config = './configs/networks/mnist_conv_big.toml'
	data_config = './configs/data/mnist.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 2

    [ca.parameters]
		[ca.parameters.level]
			neu = 5
			fc = 3		# 0,1,2
			conv = 3	# 0,1,2,3,4
			idm = 5	
			ids = 5
			eps = 5
			prop = 5

		[ca.parameters.range] # 0~1
			neu = [0.4,0.8]
			fc = [0,1]
    		conv = [0.25,0.75]
			idm = [0.4,0.8]
			ids = [0.6,1.0]
			eps = [0.4,0.8]
			prop = [0,1]


	#[ca.constraints]
		#value = ['fc=0 => conv!=0',
		#'(fc=2 && conv=0 && idm=0) => neu<4']

[train]
	epoches = 10

[verify]
	eps = 0.02
	time = 14400
	memory = '64G'
	verifiers = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify']

[dispatch]
	mode = 'slurm'

	[dispatch.slurm]
		nodes = ['slurm1','slurm2','slurm3','slurm4','slurm5']
		task_per_node = [7,7,7,7,3]
		reservation = 'dls2fc_7'