network_name = "mnist_dense50x2"
image_shape = [1, 1, 28, 28]
image_shape_mode = "NCHW"
source_model = "configs/networks/mnist_dense50x2.onnx"
source_distillation_config = "configs/networks/mnist_dense50x2.toml"
data_config = "configs/data/mnist.toml"
veri_time = 14400
veri_mem = 64
verifiers = [ "neurify",]

[dis_threshold]
type = "loss"
value = [ 0.01, 0.01,]


[factor]
[factor.architecture]
neuron_bins = 10
layer_depth_step = 1
layer_types = ['FC','Conv']
[factor.property]
count = 5
epsilons = [0.01,0.02,0.05,0.1,0.2]
[factor.other]
weight_value_repeats = 2