name = 'mnist_tiny'

[dnn]
	artifact = 'MNIST'
	onnx = './configs/networks/mnist_3x50.onnx'
	r4v_config = './configs/networks/mnist_3x50.toml'

[ca]
	strength = 2

	[ca.parameters]
		[ca.parameters.level]
			neu = 3
			fc = 3		# 0,1,2,3

		[ca.parameters.range] # 0~1
			neu = ['1/3','1']
			fc = ['1/3','1']

[train]
	epochs = 2
	drop_scheme = 'random'
	add_scheme = 'last_same_relu' # if range is greater than 1
	
	[train.dispatch]
		platform = 'local'
		gpu = false


[verify]
	eps = 0.02
	time = 60
	memory = '2G'

	[verify.verifiers]
		SwarmHost = ['abcrown']

	[verify.dispatch]
		platform = 'local'