name = 's1_cifar_convbig'

[dnn]
	artifact = 'CIFAR10'
	onnx = "./configs/networks/cifar_conv_big.onnx"
	r4v_config = "./configs/networks/cifar_conv_big.toml"
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 2

    [ca.parameters]
		[ca.parameters.level]
			neu = 5
			fc = 3
    		conv = 5
			idm = 5
			ids = 5
			eps = 5
			prop = 5

		[ca.parameters.range]
			neu = [0.2,1.0]
			fc = [0,1]
    		conv = [0,1]
			idm = [0.2,1.0]
			ids = [0.2,1.0]
			eps = [0.2,1.0]
			prop = [0,4]
	
	[ca.constraints]
		value = ['fc=0 => conv!=0',
			  	'fc=2 && conv=0 => neu !=4']

[train]
	epochs = 10
	drop_scheme = 'random'
	
	[train.dispatch]
		nb_gpus = 1
		platform = "slurm"
		exclude = """ai01,ai02,ai03,ai04,ai05,\
				   affogato13,affogato14,affogato15,\
				   adriatic03,adriatic04,adriatic05,adriatic06,\
				   lynx01,lynx02,lynx04,lynx05,lynx06,lynx07,cheetah01"""


[verify]
	debug = true
	eps = 0.02
	time = 14400
	memory = '64G'
	[verify.verifiers]
		DNNV = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex','marabou','nnenum','mipverify','verinet']
		DNNF = ['default']

	[verify.dispatch]
		platform = "slurm"
		nb_cpus = 6
		nodes = ['cortado01','cortado02','cortado03','cortado05','cortado06','cortado07','cortado08','cortado09','cortado10']
		task_per_node = 7