name = 's1_mnist_convbig'

[dnn]
	artifact = 'MNIST'
	onnx = './configs/networks/mnist_conv_big.onnx'
	r4v_config = './configs/networks/mnist_conv_big.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 2

	[ca.parameters]
		[ca.parameters.level]
			neu = 5
			fc = 3		# 0,1,2
			conv = 5	# 0,1,2,3,4
			idm = 5	
			ids = 5
			eps = 5
			prop = 5

		[ca.parameters.range] # 0~1
			neu = [0.2,1.0]
			fc = [0,1]
    		conv = [0,1]
			idm = [0.2,1.0]
			ids = [0.2,1.0]
			eps = [0.2,1.0]
			prop = [0,4]

	[ca.constraints]
		value = ['fc=0 => conv!=0',
		'(fc=2 && conv=0 && idm=0) => neu<4']

[train]
	epochs = 10
	drop_scheme = 'random'

	[train.dispatch]
		nb_gpus = 1
		platform = "slurm"
		exclude = 'ai06,affogato11,affogato12,affogato13,affogato14,affogato15,lynx01,lynx02,lynx03,lynx04,lynx05,lynx06,lynx07,ristretto01,ristretto02'


[verify]
	debug = true
	skip_layers = 3
	eps = 0.02
	time = 14400
	memory = '64G'
	[verify.verifiers]
		DNNV = ['eran_deepzono','eran_deeppoly','eran_refinezono','eran_refinepoly','neurify','planet','bab','bab_sb','reluplex','marabou','nnenum','mipverify','verinet']
		DNNF = ['default']

	[verify.dispatch]
		platform = "slurm"
		reservation = "dx3yy_28"
		nb_cpus = 6
		nodes = ['cortado04','cortado05','cortado06','cortado07','cortado08','cortado09','cortado10']
		task_per_node = 7
